# Titre et description
title: Rapport besoin 
description: Rapport de la phase besoin 
locale: fr_FR
baseurl: "/lab-rapport"

# Collections
collections:
  chapitres:
    output: true
    permalink: /:title.html
